name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Set Git config
        run: |
          git config --global user.name "Uzair-A-Jokhio"
          git config --global user.email "uzairarifjokhio@gmail.com"

      - name: Copy app files to root (if needed)
        run: |
          if [ -d space ]; then
            cp -r space/* ./
          fi

      - name: Commit changes
        run: |
          git add .
          git commit -m "Deploying to HF Spaces" || echo "No changes to commit"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://Uzair-JK:${HF_TOKEN}@huggingface.co/spaces/Uzair-JK/troubleshooting-agent
          git push origin main
